# SPDX-License-Identifier: GPL-2.0-only

dtb-$(TARGET_ARM64) += \
	stm32mp215f-dk-ca35tdcid-ostl.dtb \
	stm32mp215f-dk-ca35tdcid-ostl-m33-examples.dtb \
	stm32mp215f-dk-perf-rt.dtb \
	stm32mp215f-dk-psci-osi.dtb \
	stm32mp235f-ev1-stpmic2l-ca35tdcid-ostl.dtb \
	stm32mp257f-dk-ca35tdcid-ostl.dtb \
	stm32mp257f-dk-ca35tdcid-ostl-m33-examples.dtb \
	stm32mp257f-dk-perf-rt.dtb \
	stm32mp257f-ev1-ca35tdcid-ostl.dtb \
	stm32mp257f-ev1-ca35tdcid-ostl-m33-examples.dtb \
	stm32mp257f-ev1-ca35tdcid-ostl-m33-examples-sram.dtb \
	stm32mp257f-ev1-perf-rt.dtb \
	stm32mp257f-ev1-psci-osi.dtb \
	stm32mp257f-ev1-stpmic2l-ca35tdcid-ostl.dtb \
	stm32mp257f-ev1-tampers.dtb