# SPDX-License-Identifier: GPL-2.0-only

dtb-$(TARGET_ARM32) += \
	stm32mp135f-dk-ostl.dtb \
	stm32mp135f-dk-ostl-osi.dtb \
	stm32mp135f-dk-perf-rt.dtb \
	stm32mp135f-dk-pmic1ld-ostl.dtb \
	stm32mp157f-dk2-ostl.dtb \
	stm32mp157f-dk2-ostl-osi.dtb \
	stm32mp157f-dk2-perf-rt.dtb \
	stm32mp157f-ev1-ostl.dtb \
	stm32mp157f-ev1-ostl-osi.dtb \
	stm32mp157f-ev1-perf-rt.dtb
